// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';


const SUPABASE_URL = "https://dqasegfxeyngwbqvhwuz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRxYXNlZ2Z4ZXluZ3dicXZod3V6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3NDY3MzQsImV4cCI6MjA3MjMyMjczNH0.OR_54AhdZlxmAtJCYojTMtLEb44I4ol5Cx3q6Ipl8PU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});